-- ============================================================================
-- Frontier Radar · 0011_user_feedback_events.sql
-- 个性化推荐阶段：匿名用户反馈事件。
--
-- 目标：
--  - 不要求登录即可开始积累推荐训练数据；
--  - visitor_id 由浏览器本地生成 UUID，未来登录后可再做身份合并；
--  - 客户端不直接写表，统一通过服务端 /api/feedback 写入。
-- ============================================================================

create table if not exists public.user_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  item_id uuid not null references public.items(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'interested',
      'not_interested',
      'open_source',
      'open_detail',
      'dwell'
    )
  ),
  dwell_ms integer check (dwell_ms is null or (dwell_ms >= 0 and dwell_ms <= 3600000)),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_user_events_visitor_time
  on public.user_events (visitor_id, created_at desc);

create index if not exists idx_user_events_item_time
  on public.user_events (item_id, created_at desc);

create index if not exists idx_user_events_type_time
  on public.user_events (event_type, created_at desc);

-- 客户端不直接访问该表；服务端使用 service_role 写入。
revoke all on public.user_events from anon, authenticated;
grant select, insert, update, delete on public.user_events to service_role;
grant usage, select on sequence public.user_events_id_seq to service_role;
